import Brand from './components/Brand';
import ServiceStatus,{BackendNotice} from './pages/ServiceStatus';
import React from 'react';
import Profile from './pages/Profile';
import Auth from './pages/Auth';
import Details from './pages/TripDetails';
import Saved from './pages/SavedTrips';
import Plan from './pages/PlanTrip';
import Home from './pages/Home';
import {useState,useEffect} from 'react';
import {Routes,Route,Link,NavLink,useNavigate,useParams} from 'react-router-dom';
import {Sparkles,ArrowUpRight,ArrowRight,MapPin,CalendarDays,Wallet,Users,Compass,Heart,Mountain,Utensils,Camera,Leaf,Menu,X,Plus,Check,CloudSun,Download,RefreshCw,Send,Map,Hotel,Train,Trash2,ChevronRight,LogOut} from 'lucide-react';
import api,{LIVE} from './services/api';import {destinations,sampleTrip,demoReplan} from './services/planner';import {useAuth} from './context/AuthContext';
const money=n=>'₹'+Math.round(n).toLocaleString('en-IN');
function localTrips(){try{return JSON.parse(localStorage.getItem('tripcraft_trips')||'[]')}catch{return []}}
function App(){const [trips,setTrips]=useState(localTrips),[notice,setNotice]=useState('');const {user,logout}=useAuth();const [menu,setMenu]=useState(false);useEffect(()=>{if(LIVE&&user)api.get('/trips').then(r=>setTrips(r.data)).catch(()=>setNotice('Could not load saved trips. Please try again.'));else setTrips(localTrips());},[user]);useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(t)}},[notice]);async function save(trip){if(LIVE){if(!user)throw new Error('Please sign in to save trips.');const {data}=await api.post('/trips',trip);setTrips(p=>[data,...p.filter(x=>x.id!==data.id)]);return data;}const next=[trip,...trips.filter(t=>t.id!==trip.id)];localStorage.setItem('tripcraft_trips',JSON.stringify(next));setTrips(next);return trip;}async function remove(id){try{if(LIVE)await api.delete(`/trips/${id}`);const next=trips.filter(t=>t.id!==id);if(!LIVE)localStorage.setItem('tripcraft_trips',JSON.stringify(next));setTrips(next);setNotice('Trip deleted.');}catch{setNotice('Could not delete your trip. Try again.')}}return <><header className="header"><Brand/><nav className={menu?'nav open':'nav'} onClick={()=>setMenu(false)}><NavLink to="/" end>Discover</NavLink><NavLink to="/plan">Craft a trip</NavLink><NavLink to="/trips">My trips</NavLink></nav><div className="header-actions">{user?<><Link className="signin" to="/profile">{user.name.split(' ')[0]}</Link><button className="icon-button" title="Sign out" onClick={logout}><LogOut size={18}/></button></>:<Link className="signin" to="/login">Log in</Link>}<Link className="button small" to="/plan">Craft My Trip <ArrowUpRight size={16}/></Link><button className="mobile-menu icon-button" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></div></header><BackendNotice/><main><Routes><Route path="/status" element={<ServiceStatus/>}/><Route path="/" element={<Home/>}/><Route path="/explore" element={<Home/>}/><Route path="/plan" element={<Plan save={save} notify={setNotice}/>}/><Route path="/trips" element={<Saved trips={trips} remove={remove}/>}/><Route path="/dashboard" element={<Saved trips={trips} remove={remove}/>}/><Route path="/trip/:id" element={<Details trips={trips} save={save} notify={setNotice}/>}/><Route path="/login" element={<Auth mode="login"/>}/><Route path="/signup" element={<Auth mode="signup"/>}/><Route path="/profile" element={<Profile trips={trips}/>}/><Route path="*" element={<div className="empty"><Compass/><h1>A little off the beaten path.</h1><Link className="button" to="/">Back to discover</Link></div>}/></Routes></main><footer><Brand footer/><span>Find a route that feels like yours.</span><small>Your days. Your discoveries. © {new Date().getFullYear()} TripCraft</small></footer>{notice&&<div className="toast" role="status"><Check size={18}/>{notice}</div>}</>}

export default App;
