import React from 'react';
import {useBackendStatus} from '../context/BackendStatus';
import {useState,useEffect} from 'react';
import {Routes,Route,Link,NavLink,useNavigate,useParams} from 'react-router-dom';
import {Sparkles,ArrowUpRight,ArrowRight,MapPin,CalendarDays,Wallet,Users,Compass,Heart,Mountain,Utensils,Camera,Leaf,Menu,X,Plus,Check,CloudSun,Download,RefreshCw,Send,Map,Hotel,Train,Trash2,ChevronRight,LogOut} from 'lucide-react';
import api,{LIVE} from '../services/api';import {destinations,sampleTrip,demoReplan} from '../services/planner';import {useAuth} from '../context/AuthContext';
const money=n=>'₹'+Math.round(n).toLocaleString('en-IN');
function Auth({mode}){const {status}=useBackendStatus();const {authenticate}=useAuth();const nav=useNavigate();const [values,setValues]=useState({name:'',email:'',password:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();if(LIVE&&status&&!status.features.accounts){setError('Accounts are awaiting activation. View service status for updates.');return;}if(!LIVE){setError('Account creation is available when the TripCraft backend is connected. You can explore and save demo trips without an account.');return;}setBusy(true);try{await authenticate(mode,values);nav('/dashboard')}catch(e){setError(e.response?.data?.message||'Could not sign in. Please try again.')}finally{setBusy(false)}}return <div className="auth-page"><div className="auth-image"><img src="/images/bali.jpg" alt="Bali rice terraces"/><div><h1>Your next chapter<br/>starts somewhere new.</h1><p>Craft your perfect journey with AI.</p></div></div><div className="auth-form"><img className="auth-logo" src="/images/tripcraft-logo.png" alt="TripCraft"/><h1>{mode==='signup'?'A world of possibilities.':'Welcome back, wanderer.'}</h1><p>{mode==='signup'?'Create your TripCraft account.':'Your next adventure is waiting.'}</p>{LIVE&&status&&!status.features.accounts&&<p className="mode-note">Accounts are awaiting activation. <Link to="/status">View service status →</Link></p>}<form onSubmit={submit}>{mode==='signup'&&<label>Your name<input required autoComplete="name" value={values.name} onChange={e=>setValues({...values,name:e.target.value})}/></label>}<label>Email<input required type="email" autoComplete="email" value={values.email} onChange={e=>setValues({...values,email:e.target.value})}/></label><label>Password<input required type="password" minLength={8} autoComplete={mode==='signup'?'new-password':'current-password'} value={values.password} onChange={e=>setValues({...values,password:e.target.value})}/></label>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy||(LIVE&&status&&!status.features.accounts)} className="button full">{busy?'Please wait…':mode==='signup'?'Create account':'Log in'}<ArrowRight size={17}/></button></form><p>{mode==='signup'?'Already a member?':'New to TripCraft?'} <Link to={mode==='signup'?'/login':'/signup'}>{mode==='signup'?'Log in':'Create an account'}</Link></p>{!LIVE&&<div className="mode-note">This preview runs in demo mode. <Link to="/plan">Explore without an account →</Link></div>}</div></div>}

export default Auth;
