import React from 'react';
import {MapPin,ArrowUpRight,Star,Clock} from 'lucide-react';
export function safeLink(url){try{const u=new URL(url);return u.protocol==='https:'?u.href:null}catch{return null}}
export default function CityExplorer({trip}){
 const places=trip.cityPlaces||[];
 return <section className="panel city-explorer"><div className="kicker">EXPLORE YOUR DESTINATION</div><h2>More of {trip.resolvedDestination||trip.destination}</h2><p>{places.length?'Real attractions from public destination guides. Your itinerary uses a different selection each day.':'This trip is an offline sample. The live planner finds famous sights and alternatives for the city you choose.'}</p><div className="city-place-grid">{places.map(p=><article className="city-place" key={p.id}><div className="place-tags">{p.famous&&<span><Star size={13}/> Guide highlight</span>}<span>{p.scheduled?'In your itinerary':'Another option'}</span></div><h3>{p.name}</h3><p><MapPin size={14}/> {p.area}</p><p>{p.description}</p><small><Clock size={13}/> Allow about {p.durationMinutes} minutes</small><p className="muted">{p.visitNote}</p><a className="text-link" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.name+', '+trip.resolvedDestination)}`}>Locate this place <ArrowUpRight size={15}/></a></article>)}</div></section>
}
export function ResearchSources({trip}){
 const sources=(trip.sources||[]).filter(s=>safeLink(s.url));
 if(!sources.length)return null;
 return <section className="panel research-sources"><h3>City research sources</h3><p>Research retrieved {trip.researchAt?new Date(trip.researchAt).toLocaleDateString():''}. Schedules, durations and costs are planning estimates; confirm details with each attraction.</p><p className="muted">{trip.attribution}</p><div>{sources.map((s,i)=><a key={i} href={safeLink(s.url)} target="_blank" rel="noreferrer">{s.title||`Source ${i+1}`} <ArrowUpRight size={13}/></a>)}</div>{trip.searchAttribution&&<iframe className="search-attribution" title="Google Search suggestions" sandbox="allow-popups allow-popups-to-escape-sandbox" srcDoc={trip.searchAttribution}/>}</section>
}
export function ActivityInfo({activity}){return <>{activity.description&&<p className="activity-description">{activity.description}</p>}<div className="activity-facts">{activity.famous&&<span>★ Guide highlight</span>}{activity.area&&<span>{activity.area}</span>}{activity.durationMinutes&&<span>{activity.durationMinutes} min visit</span>}{activity.travelMinutes>0&&<span>~{activity.travelMinutes} min transfer</span>}</div>{activity.visitNote&&<p className="muted">{activity.visitNote}</p>}{safeLink(activity.mapUrl)&&<a className="text-link activity-map" href={safeLink(activity.mapUrl)} target="_blank" rel="noreferrer">View place on map <ArrowUpRight size={14}/></a>}</>}
